source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
	pod 'SDOSL10n', :path => '../../', :inhibit_warnings => false
end

target 'AppTest' do
	shared_pods
end
